#!/bin/bash

path="/run/shm/cephmon"

[[ $0 =~ ([^_]*)$ ]]
pool=$BASH_REMATCH

if [[ $1 == "config" ]]; then
  echo "graph_title CEPH $pool traffic"
  echo "graph_category ceph"
  echo "graph_vlabel Bytes/sec"
  echo "graph_args -l 0"
  echo "graph_scale yes"
  echo "graph_info Ceph traffic in the \"$pool\" pool"
  echo "read.label Read"
  echo "read.info Average bytes/sec read the last 5 minutes."
  echo "write.label Write"
  echo "write.info Average bytes/sec write the last 5 minutes."
  exit 0
fi

ps aux | grep -v grep | grep "ceph-collector.sh $pool" > /dev/null
if [[ $? -eq 1 ]]
then
  # Cannot start process here, as it is killed by muning. Needs to be started
  # elsewhere. Cron maybe? For now, just return -1
  #/usr/local/sbin/ceph-collector.sh $pool &
  echo "read.value -1"
  echo "write.value -1"
else
  totRead=0
  i=0
  
  for line in $(tail -n 300 "$path/ceph-$pool-read"); do
    totRead=$((totRead + line))
    ((i++))
  done
  
  echo "read.value $(($totRead/$i))"
  
  totWrite=0
  i=0
  
  for line in $(tail -n 300 "$path/ceph-$pool-write"); do
    totWrite=$((totWrite + line))
    ((i++))
  done
  
  echo "write.value $(($totWrite/$i))"
fi
