#!/bin/bash
set -e

if [ "$1" = "config" ]; then
	
	echo 'graph_title CEPH OSDs'
	echo 'graph_category ceph'
	echo 'graph_vlabel number'
	echo 'graph_info CEPH OSD up/down status'
	echo 'graph_scale no'
	echo 'graph_args --base 1000 -l 0'

	echo "osds.label Total"
	echo "up.label Up"
	echo "in.label In"

	exit 0
fi

osds=0
ups=0
ins=0

for osd in $(ceph report 2> /dev/null  | jq '.["osdmap"]["osds"][]' -c); do
  ((osds += 1))
  if [[ $(echo "$osd" | jq -r '.["up"]') -eq '1' ]]; then
    ((ups += 1))
  fi 
  if [[ $(echo "$osd" | jq -r '.["in"]') -eq '1' ]]; then
    ((ins += 1))
  fi 
done

echo "osds.value $osds" 
echo "up.value $ups" 
echo "in.value $ins" 
