#!/bin/bash

if [[ $1 == "config" ]]; then
  echo "graph_title CEPH Storage usage"
  echo "graph_category ceph"
  echo "graph_vlabel Bytes"
  echo "graph_args -l 0"
  echo "graph_scale yes"
  echo "graph_info Storage size of each ceph pool"
  
  for pool in $(ceph osd pool ls); do
    pn=${pool//./_}
    echo ${pn}.label $pool
    echo ${pn}.info Disk space used by the $pool pool.
  done
  exit 0
fi

declare -A factors
factors[B]=1
factors[KiB]=1024
factors[MiB]=1048576
factors[GiB]=1073741824
factors[TiB]=1099511627776
factors[PiB]=1125899906842624

for pool in $(ceph osd pool ls); do
  pn=${pool//./_}
  
  data=$(rados df --pool $pool | grep $pool | awk '{print $2}')
  if [[ $data =~ ([0-9.\]+)([KMGTP]?i?B) ]]; then
    echo $pn.value $(echo "${BASH_REMATCH[1]} * ${factors[${BASH_REMATCH[2]}]}" | bc)
  else
    echo $pn.value U 
  fi
done
