#!/bin/bash
set -e

pools=$(ceph tell "mon.$(hostname)" report 2> /dev/null  | jq '.["osdmap"]["pools"][]' -c)

if [[ $1 == "config" ]]; then
  echo "graph_title CEPH Activity - IOPS"
  echo "graph_category ceph"
  echo "graph_vlabel IOPS read(+)/write(-)"
  echo "graph_args -l 0"
  echo "graph_scale yes"
  echo "graph_info Traffic to/from ceph-pools"
  echo "graph_width 550"
  
  for pool in $pools; do
    realname=$(echo "$pool" | jq -r '.["pool_name"]')
    name=${realname//./_}
    name=${name//-/_}
    
    echo "${name}write.label $realname"
    echo "${name}write.type DERIVE"
    echo "${name}write.min 0"
    echo "${name}write.graph no"
    echo "${name}read.label $realname"
    echo "${name}read.type DERIVE"
    echo "${name}read.min 0"
    echo "${name}read.negative ${name}write"
  done
  exit 0
fi

declare -A poolids
for pool in $pools; do
  poolids[$(echo "$pool" | jq -r '.["pool"]')]=$(echo "$pool" | jq -r '.["pool_name"]')
done

for data in $(ceph tell "mon.$(hostname)" report 2> /dev/null  | jq '.["pool_stats"][]' -c); do
  name=${poolids[$(echo "$data" | jq -r '.["poolid"]')]}
  name=${name//./_}
  name=${name//-/_}
  
  iowrite=$(echo "$data" | jq '.["stat_sum"]["num_write"]')
  ioread=$(echo "$data" | jq '.["stat_sum"]["num_read"]')
  echo "${name}write.value ${iowrite}"
  echo "${name}read.value ${ioread}"
done
