#!/bin/bash
set -e

pools=$(ceph tell "mon.$(hostname)" report 2> /dev/null  | jq '.["osdmap"]["pools"][]' -c)

if [[ $1 == "config" ]]; then
  echo "graph_title CEPH Objects"
  echo "graph_category ceph"
  echo "graph_vlabel Objects"
  echo "graph_args -l 0"
  echo "graph_scale yes"
  echo "graph_info The number of objects in each ceph pool"
  
  for pool in $pools; do
    name=$(echo "$pool" | jq -r '.["pool_name"]')
    name=${name//./_}
    name=${name//-/_}
    
    echo "${name}.label $(echo "$pool" | jq -r '.["pool_name"]')"
    echo "${name}.info Objects in the $(echo "$pool" | jq -r '.["pool_name"]') pool."
  done
  exit 0
fi

declare -A poolids
for pool in $pools; do
  poolids[$(echo "$pool" | jq -r '.["pool"]')]=$(echo "$pool" | jq -r '.["pool_name"]')
done

for data in $(ceph tell "mon.$(hostname)" report 2> /dev/null | jq '.["pool_stats"][]' -c); do
  name=${poolids[$(echo "$data" | jq -r '.["poolid"]')]}
  name=${name//./_}
  name=${name//-/_}
  
  echo "${name}.value $(echo "$data" | jq '.["stat_sum"]["num_objects"]')"
done
