#!/bin/bash
set -e

if [ "$1" = "config" ]; then
	
	echo 'graph_title CEPH OSDs'
	echo 'graph_category ceph'
	echo 'graph_vlabel number'
	echo 'graph_info CEPH OSD up/down status'
	echo 'graph_scale no'
	echo 'graph_args --base 1000 -l 0'

	echo "osds.label Total"
	echo "up.label Up"
	echo "in.label In"

	exit 0
fi

osds=0
ups=0
ins=0

while read -r osd; do
  up=$(echo $osd | jq '.["up"]')
  in=$(echo $osd | jq '.["in"]')

  osds=$((osds + 1))
  if [ $up -eq 1 ]; then
    ups=$((ups + 1))
  fi
  if [ $in -eq 1 ]; then
    ins=$((ins + 1))
  fi
done < <(ceph insights | jq -c '.["osd_dump"]["osds"][]') 

echo "osds.value $osds" 
echo "up.value $ups" 
echo "in.value $ins" 
