#!/bin/bash
set -e

pools=$(ceph tell "mon.$(hostname)" report 2> /dev/null  | jq '.["osdmap"]["pools"][]' -c)

if [[ $1 == "config" ]]; then
  echo "graph_title CEPH Activity - Bits read/written"
  echo "graph_category ceph"
  echo "graph_vlabel bits/sec read(+)/write(-)"
  echo "graph_args -l 0"
  echo "graph_scale yes"
  echo "graph_info Read and write traffic to ceph-pools"
  echo "graph_width 550"
  
  for pool in $pools; do
    realname=$(echo "$pool" | jq -r '.["pool_name"]')
    name=${realname//./_}
    name=${name//-/_}
    
    echo "${name}write.label $realname"
    echo "${name}write.type DERIVE"
    echo "${name}write.min 0"
    echo "${name}write.graph no"
    echo "${name}read.label $realname"
    echo "${name}read.type DERIVE"
    echo "${name}read.min 0"
    echo "${name}read.negative ${name}write"
  done
  exit 0
fi

declare -A poolids
for pool in $pools; do
  poolids[$(echo "$pool" | jq -r '.["pool"]')]=$(echo "$pool" | jq -r '.["pool_name"]')
done

for data in $(ceph tell "mon.$(hostname)" report 2> /dev/null  | jq '.["pool_stats"][]' -c); do
  name=${poolids[$(echo "$data" | jq -r '.["poolid"]')]}
  name=${name//./_}
  name=${name//-/_}
  
  kbwrite=$(echo "$data" | jq '.["stat_sum"]["num_write_kb"]')
  kbread=$(echo "$data" | jq '.["stat_sum"]["num_read_kb"]')
  echo "${name}write.value $(echo "$kbwrite * 1024 * 8" | bc)"
  echo "${name}read.value $(echo "$kbread * 1024 * 8" | bc)"
done
