#!/bin/bash
set -e

if [[ $1 == "config" ]]; then
  echo 'graph_title CEPH total capacity'
  echo 'graph_category ceph'
  echo 'graph_vlabel Bytes'
  echo 'graph_info CEPH cluster capacity'
  echo 'graph_args -l 0'
  echo "capacity.label Capacity"
  echo "free.label Free"
  echo "data.label Data stored"

  exit 0
fi

data=$(ceph tell "mon.$(hostname)" report 2> /dev/null  | jq -c '.["osd_sum"]["statfs"]')

size=$(echo "$data" | jq '.["total"]')
free=$(echo "$data" | jq '.["available"]')

echo "capacity.value $size"
echo "free.value $free"
echo "data.value $((size-free))"
