#!/bin/sh

if [ "$1" = "autoconf" ]; then
	echo yes
	exit 0
fi

if [ "$1" = "config" ]; then
	echo 'graph_title CEPH capacity'
	echo 'graph_category ceph'
	echo 'graph_vlabel GB'
	echo 'graph_info CEPH cluster capacity'
	echo 'graph_args --base 1000 -l 0'
	echo "capacity.label Capacity"
	echo "used.label Raw used"
	echo "used.draw AREA"
	echo "data.label Data"
	echo "data.draw AREA"

	exit 0
fi

echo "capacity.value U"
echo "data.value U"
echo "used.value U"
