#!/bin/bash
set -e

classes=$(ceph report 2> /dev/null  | jq '.["osd_sum_by_class"]' | jq 'keys[]' -r)

if [[ $1 == "config" ]]; then
  echo "graph_title CEPH OSDs by class"
  echo "graph_category ceph"
  echo "graph_vlabel OSD's"
  echo "graph_args -l 0"
  echo "graph_scale yes"
  echo "graph_info The number of OSD's of a certain class"
  
  for class in $classes; do
    echo "${class}.label $class"
    echo "${class}.info OSD's of the $class class."
  done
  exit 0
fi

tmpfile=$(mktemp /tmp/munin-ceph-XXXXXXXX)
ceph report 2> /dev/null  | jq '.["osd_sum_by_class"]' > $tmpfile 

for class in $classes; do
  echo "${class}.value" $(cat $tmpfile | jq ".[\"$class\"][\"num_osds\"]")
done

rm $tmpfile 
