#!/bin/bash
set -e

tmpfile=$(mktemp)
ceph insights > $tmpfile

if [[ $1 == "config" ]]; then
  echo "graph_title CEPH Objects"
  echo "graph_category ceph"
  echo "graph_vlabel Objects"
  echo "graph_args -l 0"
  echo "graph_scale yes"
  echo "graph_info The number of objects in each ceph pool"
  
  for pool in $(jq -c '.["df"]["pools"][]' $tmpfile); do
    name=$(echo $pool | jq -r '.["name"]')
    name=${name//-/_}
    name=${name//./_}
    
    echo ${name}.label $(echo $pool | jq -r '.["name"]')
    echo ${name}.info Objects in the $(echo $pool | jq -r '.["name"]') pool.
  done
  rm $tmpfile
  exit 0
fi

for pool in $(jq -c '.["df"]["pools"][]' $tmpfile); do
  name=$(echo $pool | jq -r '.["name"]')
  name=${name//./_}
  name=${name//-/_}
  
  echo ${name}.value $(echo $pool | jq '.["stats"]["objects"]')
done

rm $tmpfile
