#!/bin/bash

path="/run/shm/cephmon"

[[ $0 =~ ([^_]*)$ ]]
pool=$BASH_REMATCH

if [[ $1 == "config" ]]; then
  echo "graph_title CEPH $pool IOPS"
  echo "graph_category ceph"
  echo "graph_vlabel IOPS"
  echo "graph_args -l 0"
  echo "graph_scale yes"
  echo "graph_info Ceph IOPS for the \"$pool\" pool"
  echo "read.label IOPS Read"
  echo "read.info Average IOPS read for the \"$pool\" pool"
  echo "write.label IOPS Write"
  echo "write.info Average IOPS written for the \"$pool\" pool"
  exit 0
fi


ps aux | grep -v grep | grep "ceph-collector.sh $pool" > /dev/null
if [[ $? -eq 1 ]]
then
  # Cannot start process here, as it is killed by muning. Needs to be started
  # elsewhere. Cron maybe? For now, just return -1
  #/usr/local/sbin/ceph-collector.sh $pool &
  echo "read.value U"
  echo "write.value U"
else
  totiopsR=0
  i=0

  for line in $(tail -n 300 "$path/ceph-$pool-iopsR"); do
    totiopsR=$((totiopsR+ line))
    ((i++))
  done
  
  echo "read.value $(($totiopsR/$i))"

  totiopsW=0
  i=0

  for line in $(tail -n 300 "$path/ceph-$pool-iopsW"); do
    totiopsW=$((totiopsW+ line))
    ((i++))
  done
  
  echo "write.value $(($totiopsW/$i))"
fi
