#!/bin/bash

if [[ $1 == "config" ]]; then
  echo "graph_title Nova RAM summary"
  echo "graph_category openstack"
  echo "graph_vlabel Bytes of RAM"
  echo "graph_args -l 0 --base 1024"
  echo "graph_scale yes"
  echo "graph_info Amount of available and allocated RAM"
  echo "total.label Total"
  echo "total.info Total RAM available"
  echo "used.label Allocated"
  echo "used.info Allocated RAM"
  exit 0
fi

PROVIDER_ID=$(openstack resource provider list -f value | grep -E "$(hostname -f) " | cut -d' ' -f1)
eval $(openstack resource provider inventory show -f shell $PROVIDER_ID MEMORY_MB)

echo "total.value $(($total * 1024 * 1024))"
echo "used.value $(($used * 1024 * 1024))"
