#!/bin/bash

if [[ $1 == "config" ]]; then
  echo "graph_title Nova CPU summary"
  echo "graph_category openstack"
  echo "graph_vlabel VCPU"
  echo "graph_args -l 0"
  echo "graph_scale yes"
  echo "graph_info Amount of available, allocated CPU's"
  echo "total.label Total"
  echo "total.info Total CPU's available"
  echo "used.label Allocated"
  echo "used.info Allocated CPU's"
  exit 0
fi

PROVIDER_ID=$(openstack resource provider list -f value | grep -E "$(hostname -f) " | cut -d' ' -f1)
eval $(openstack resource provider inventory show -f shell $PROVIDER_ID VCPU)

echo "total.value $total"
echo "used.value $used"
