#!/bin/bash

if [[ $1 == "config" ]]; then
  echo "graph_title Nova VM's" 
  echo "graph_category openstack"
  echo "graph_vlabel VM's"
  echo "graph_args -l 0 --base 1000"
  echo "graph_scale yes"
  echo "graph_info Number of running nova VM's"
  echo "used.label VM's"
  echo "used.info Number of VM's"
  exit 0
fi

running_vms=$(openstack server list -f value -c ID --all-projects --host $(hostname) | wc -l)

echo "used.value $running_vms"
