#!/bin/bash

if [[ $1 == "config" ]]; then
  echo "graph_title Nova RAM summary"
  echo "graph_category openstack"
  echo "graph_vlabel Bytes of RAM"
  echo "graph_args -l 0 --base 1024"
  echo "graph_scale yes"
  echo "graph_info Amount of available and allocated RAM"
  echo "total.label Total"
  echo "total.info Total RAM available"
  echo "used.label Allocated"
  echo "used.info Allocated RAM"
  exit 0
fi

eval $(openstack hypervisor show $(hostname -f) -f shell)

echo "total.value $(($memory_mb * 1024 * 1024))"
echo "used.value $(($memory_mb_used * 1024 * 1024))"
