#!/bin/bash

if [[ $1 == "config" ]]; then
  echo "graph_title Nova RAM summary"
  echo "graph_category openstack"
  echo "graph_vlabel RAM"
  echo "graph_args -l 0"
  echo "graph_scale yes"
  echo "graph_info Amount of available, enabled and allocated RAM"
  echo "total.label Total"
  echo "total.info Total RAM available"
  echo "enabled.label Enabled"
  echo "enabled.info Total RAM on enabled hosts"
  echo "used.label Allocated"
  echo "used.info Allocated RAM"
  exit 0
fi

#totalRAM=0
#enabledRAM=0
#usedRAM=0
#
#for node in $(nova service-list | grep " nova " | awk '{ print $6";"$10}'); do 
#  [[ $node =~ (.*)\;(.*) ]]
#  nodename=${BASH_REMATCH[1]}
#  nodestatus=${BASH_REMATCH[2]}
#  
#  total=$(nova host-describe $nodename | grep total)
#  used=$(nova host-describe $nodename | grep used_now)
#   
#  tRAM=$(echo "$total" | awk '{print $8}')
#  uRAM=$(echo "$used" | awk '{print $8}')
#  
#  ((usedRAM += $uRAM))
#  ((totalRAM += $tRAM))
#  
#  if [[ $nodestatus == "enabled" ]]; then
#    ((enabledRAM += $tRAM))
#  fi
#done
#
#echo used.value $(($usedRAM * 1024 * 1024))
#echo total.value $(($totalRAM * 1024 * 1024))
#echo enabled.value $(($enabledRAM * 1024 * 1024))
echo "total.value U"
echo "enabled.value U"
echo "used.value U"
