#!/bin/bash

[[ $0 =~ ([^_]*)$ ]]
net=$BASH_REMATCH

if [[ $1 == "config" ]]; then
  echo "graph_title IP allocations for $net"
  echo "graph_category openstack"
  echo "graph_vlabel IP's"
  echo "graph_args -l 0"
  echo "graph_scale yes"
  echo "graph_info Amount of allocated and used IP's for the network $net"
  echo "total.label Available"
  echo "total.info Number of available IPv4 addresses"
  echo "used.label Used IPv4"
  echo "used.info Number of used IPv4 addresses"
  echo "used6.label Used IPv6"
  echo "used6.info Number of used IPv6 addresses"
  exit 0
fi

used4=0
used6=0
total=0

for subnet in $(openstack ip availability show ntnu-global -f value -c subnet_ip_availability | tr "'" '"' | jq '.[]' -c); do
    version=$(echo "$subnet" | jq '.["ip_version"]')
    if [[ $version -eq 4 ]]; then
      ((total+=$(echo "$subnet" | jq '.["total_ips"]')))
      ((used4+=$(echo "$subnet" | jq '.["used_ips"]')))
    elif [[ $version -eq 6 ]]; then
      ((used6+=$(echo "$subnet" | jq '.["used_ips"]')))
    fi
done

echo "used.value $used4" 
echo "used6.value $used6" 
echo "total.value $total" 
