#!/bin/bash

if [[ $1 == "config" ]]; then
  echo "graph_title Magnum nodes"
  echo "graph_category openstack"
  echo "graph_vlabel Nodes"
  echo "graph_args -l 0"
  echo "graph_scale yes"
  echo "graph_info Total amount of master and worker nodes"

  echo "masters.label master nodes"
  echo "workers.label worker nodes"

  exit 0
fi

masters=$((openstack coe cluster list -f value -c master_count | tr '\n' '+'; echo 0) | bc)
workers=$((openstack coe cluster list -f value -c node_count | tr '\n' '+'; echo 0) | bc)

echo "masters.value $masters"
echo "workers.value $workers"
