#!/bin/bash

if [[ $1 == "config" ]]; then
  echo "graph_title VM OS types"
  echo "graph_category openstack"
  echo "graph_vlabel #"
  echo "graph_args -l 0"
  echo "graph_scale yes"
  echo "graph_info Amount of virtual machines featuring a certain OS"

  while read -r name; do
    label=${name// /_}
    label=${label//./_}
    echo "${label}.label ${name}"
  done < <(openstack server list -c Image -f value --all --limit 100000 | \
    grep -Eo '(Ubuntu\ (Server\ )?[0-9]{2}.[0-9]{2}|CentOS\ [0-9](\.[0-9])?|Windows\ (Server\ )?[0-9]+|Debian\ [0-9]+|Kali|AlmaLinux\ [0-9](\.[0-9])?|Rocky\ Linux\ [0-9](\.[0-9])?)' | sort | uniq)

  exit 0
fi

while read -r line; do
  no=$(echo "$line" | awk '{ print $1 }')
  name=$(echo "$line" | awk '{for (i=2; i<NF; i++) printf $i " "; print $NF}')
  label=${name// /_}
  label=${label//./_}

  echo "${label}.value ${no}"
done < <(openstack server list -c Image -f value --all --limit 100000 | \
  grep -Eo '(Ubuntu\ (Server\ )?[0-9]{2}.[0-9]{2}|CentOS\ [0-9](\.[0-9])?|Windows\ (Server\ )?[0-9]+|Debian\ [0-9]+|Kali|AlmaLinux\ [0-9](\.[0-9])?|Rocky\ Linux\ [0-9](\.[0-9])?)' | sort | uniq -c)
