#!/bin/bash

if [[ $1 == "config" ]]; then
  echo "graph_title Openstack loadbalancer statuses"
  echo "graph_category openstack"
  echo "graph_vlabel loadbalancers"
  echo "graph_args -l 0"
  echo "graph_scale yes"
  echo "graph_info Amount of running loadbalancers with a certain status"

  while read -r s; do    
    echo "${s}.label $s"
    echo "${s}.info Loadbalancer with the status ${s}"
  done < <(openstack loadbalancer list -f value -c provisioning_status | sort | uniq)
  exit 0
fi

while read -r data; do    
  s=$(echo "$data" | awk '{print $2}')
  v=$(echo "$data" | awk '{print $1}')
  echo "${s}.value $v"
done < <(openstack loadbalancer list -f value -c provisioning_status | sort | uniq -c)
