#!/bin/bash

types=$(ip netns ls | cut -d '-' -f 1 | sort | uniq)

if [[ $1 == "config" ]]; then
  echo "graph_title Neutron resources"
  echo "graph_category openstack"
  echo "graph_vlabel Instances"
  echo "graph_args -l 0"
  echo "graph_scale yes"
  echo "graph_info Amount of services on the neutron-node"
  for t in $types; do 
    echo "${t}.label ${t}"
    echo "${t}.info Number of ${t} namespaces"
  done
  exit 0
fi

for t in $types; do 
  echo "${t}.value $(ip netns ls | grep -c "$t")"
done
