#!/bin/bash

if [[ $1 == "config" ]]; then
  echo "graph_title Nova hypervisors"
  echo "graph_category openstack"
  echo "graph_vlabel hypervisors"
  echo "graph_args -l 0"
  echo "graph_scale yes"
  echo "graph_info Amount of available hypervisors"
  echo "total.label Hypervisors"
  echo "total.info Number of hypervisors"
  exit 0
fi

eval $(openstack hypervisor stats show -f shell)

echo "total.value $count"
