#!/bin/bash

if [[ $1 == "config" ]]; then
  echo "graph_title IP utilization"
  echo "graph_category openstack"
  echo "graph_vlabel Percent"
  echo "graph_args -l 0"
  echo "graph_scale no"
  echo "graph_info Amount of IPs in use from external networks"
  for net in $EXTERNALS; do
    echo ${net/\-/}.label $net
    echo ${net/\-/}.info IPs utilized from $net
  done
  exit 0
fi

for net in $EXTERNALS; do
  value=$(openstack ip availability show $net -f value -c subnet_ip_availability | grep "ip_version='4'")

  [[ $value =~ total_ips=\'([0-9]+)\' ]]
  total=${BASH_REMATCH[1]}

  [[ $value =~ used_ips=\'([0-9]+)\' ]]
  used=${BASH_REMATCH[1]}

  value=$(echo "scale=2;${used}*100/${total}" | bc)
  echo ${net/\-/}.value $value
done
