#! /usr/bin/python
import time
import sys
import yaml

statusfile = open('/var/lib/puppet/state/last_run_summary.yaml', 'r')
y = yaml.load(statusfile)

if('config' in sys.argv):
  print("graph_title Time since last puppet run")
  print("graph_category puppet")
  print("graph_vlabel Seconds")
  print("graph_args -l 0 --base 1000")
  print("graph_scale yes")
  print("graph_info Time since last puppet run")
  print("time.label Seconds")
  print("time.info Number of seconds since last puppet run.")
  sys.exit(0)

diff = time.time() - int(y['time']['last_run'])

print("time.value %d" % diff)
