#! /usr/bin/python
import sys
import yaml

statusfile = open('/var/lib/puppet/state/last_run_summary.yaml', 'r')
y = yaml.load(statusfile)

if('config' in sys.argv):
  print("graph_title Total number of puppet resources")
  print("graph_category puppet")
  print("graph_vlabel Resources")
  print("graph_args -l 0 --base 1000")
  print("graph_scale yes")
  print("graph_info Number of puppet resource at last puppet run")
  print("total.label Resources")
  print("total.info Number of resources")
  sys.exit(0)

print("total.value %s" % y['resources']['total'])
