#! /usr/bin/python
import sys
import yaml

statusfile = open('/var/lib/puppet/state/last_run_summary.yaml', 'r')
y = yaml.load(statusfile)

if('config' in sys.argv):
  print("graph_title Puppet resources")
  print("graph_category puppet")
  print("graph_vlabel Resources")
  print("graph_args -l 0 --base 1000")
  print("graph_scale yes")
  print("graph_info Puppet resource status after last puppet run")
  print("changed.label changed")
  print("changed.info changed")
  print("scheduled.label scheduled")
  print("scheduled.info scheduled")
  print("skipped.label skipped")
  print("skipped.info skipped")
  print("restarted.label restarted")
  print("restarted.info restarted")
  print("failed.label failed")
  print("failed.info failed")
  print("failed_to_restart.label failed_to_restart")
  print("failed_to_restart.info failed_to_restart")
  print("out_of_sync.label out_of_sync")
  print("out_of_sync.info out_of_sync")
  sys.exit(0)

for resource in y['resources']:
  if(resource == 'total'):
    continue
  print("%s.value %s" % (resource, y['resources'][resource]))
