#!/bin/bash

line=$(rabbitmqctl status --formatter erlang | grep processes)

if [[ $line =~ limit,([0-9]+).*used,([0-9]+) ]]; then
  limit=${BASH_REMATCH[1]}
  used=${BASH_REMATCH[2]}
fi

if [[ $1 == "config" ]]; then
  warn=$((limit * 80 / 100))
  crit=$((limit * 90 / 100))

  echo "graph_title Rabbit processes"
  echo "graph_category rabbitmq"
  echo "graph_vlabel processes"
  echo "graph_args -l 0"
  echo "graph_scale yes"
  echo "graph_info Number of running rabbitmq processes"
  echo "limit.label Processes limit"
  echo "limit.info Processes limit"
  echo "used.label Processes running"
  echo "used.info Processes running"
  echo "used.warning $warn"
  echo "used.critical $crit"
  exit 0
fi

echo "limit.value $limit"
echo "used.value $used"
